version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "telegram"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9723g4fe3m1n"
s3_prefix = "telegram"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
